name: NodeSeek 自动签到评论加鸡腿

on:
  push:
    branches:
      - main
  schedule:
    - cron: '00 16 * * *'  # UTC 16:00，对应北京时间 00:00

jobs:
  run-nodeseek-daily:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.8'

      - name: Install Chrome (official stable) and Chromedriver (auto-match)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb
          # 下载最新稳定版 Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          google-chrome --version
          # 自动下载与 Chrome 匹配的 chromedriver
          CHROME_VERSION=$(google-chrome --version | grep -oE '[0-9]+\.')
          CHROME_VERSION=${CHROME_VERSION%%.*}
          echo "Detected Chrome major version: $CHROME_VERSION"
          wget -q "https://storage.googleapis.com/chrome-for-testing-public/$(google-chrome --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')/linux64/chromedriver-linux64.zip" -O chromedriver.zip || true
          unzip -o chromedriver.zip -d /usr/local/bin/ || true
          chmod +x /usr/local/bin/chromedriver || true
          chromedriver --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install curl_cffi selenium undetected-chromedriver python-dotenv requests

      - name: Run NodeSeek script
        env:
          NS_COOKIE: ${{ secrets.NS_COOKIE }}
          NS_RANDOM: ${{ secrets.NS_RANDOM }}
          HEADLESS: "true"
        run: |
          python nodeseek_daily.py
